# Site settings
title: Romain Péchayre 
email: rpechayr@gmail.com
description: "Co-founder and CTO at Applidget"
baseurl: ""
url: "http://localhost:4000"
twitter_username: rpechayr
github_username:  rpechayr

# Build settings
markdown: kramdown
permalink: pretty
